### PR TITLE
Dominoes

### PR DESCRIPTION
**Pull request by drivera021**

### CODE REVIEW

**Comment by drivera021** [comment]
Changed first line of "/bin/dominoes/domino" to reflect location of Python. After installing on other systems, it returned "#!/Users/abw333/.virtualenvwrapper/dominoes/bin/python". I installed with Pip, not sure if that matters.

**Comment by abw333** [comment]
Hi Daniel. Thank you for submitting this pull request.

You're right that there is something wrong with the package, but I'm not entirely sure that the problem is that line. I suspect that I messed something up when uploading the package to PyPI. I will look into this today.

See this: https://stackoverflow.com/questions/2429511/why-do-people-write-usr-bin-env-python-on-the-first-line-of-a-python-script/2429517#2429517

Specifically, this: If you have several versions of Python installed, /usr/bin/env will ensure the interpreter used is the first one on your environment's $PATH. The alternative would be to hardcode something like #!/usr/bin/python; that's ok, but less flexible.

**Comment by abw333** [comment]
Hi again. I just looked into this for a few minutes, and mostly just realized how much I've forgotten and/or how much has changed about Python's package management over the last few years. :)

I installed the dominoes package using pip, but I keep on getting "command not found" when trying to run the dominoes executable. I tried restarting everything after the installation, but no luck. If you know what I might be doing wrong, let me know.

Regardless, I was able to run the executable by cloning the repository and running the file directly. Worst case, you can copy that file into your bin directory and it should work.

If you're willing to look into this in more detail to figure out exactly what the problem is, I'm willing to help with whatever you need. Thanks.

**Comment by drivera021** [comment]
Hello! As you said before, it would probably be an issue with the file that is uploaded to pip. Your solution for the finding the Python interpreter is definitely better since it supports multiple versions of Python. Thanks for reaching out!

**Pull request closed without merging**
